trigger:
  branches:
    include:
      - main

variables:
  resourceGroupName: 'sahana-learn'
  location: 'centralus'
  serviceConnection: 'my-azure-service-connection'

stages:
  - stage: DeployInfra
    displayName: 'Deploy ARM Template'
    jobs:
      - deployment: DeployArm
        displayName: 'Deploy infrastructure to Azure'
        environment: 'dev'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '$(serviceConnection)'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: '$(resourceGroupName)'
                    location: '$(location)'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
                    csmParametersFile: '$(System.DefaultWorkingDirectory)/azuredeploy.parameters.dev.json'
                    deploymentMode: 'Incremental'