trigger:
  - main

stages:
  - stage: DeployStorage
    displayName: "Stage 1 - Deploy Storage"
    jobs:
      - job: deployStorage
        displayName: "Deploy Storage Account"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            name: setOutput
            inputs:
              azureSubscription: "MyAzureConnection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group sahana-learn \
                  --template-file storage.json \
                  --parameters location=centralus

                STORAGE_NAME=$(az storage account list \
                  --resource-group sahana-learn \
                  --query "[0].name" -o tsv)

                echo "Storage account name: $STORAGE_NAME"
                echo "##vso[task.setvariable variable=storageAccountName;isOutput=true]$STORAGE_NAME"

  - stage: DeployFunctionApp
    displayName: "Stage 2 - Deploy Function App"
    dependsOn: DeployStorage
    variables:
      storageAccountName: $[stageDependencies.DeployStorage.deployStorage.outputs['setOutput.storageAccountName']]
    jobs:
      - job: deployFunctionApp
        displayName: "Deploy Function App"
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Storage account from Stage 1: $(storageAccountName)"
            displayName: "Print storage name from Stage 1"
          - task: AzureCLI@2
            inputs:
              azureSubscription: "MyAzureConnection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group sahana-learn \
                  --template-file functionapp.json \
                  --parameters functionAppName=myfunc location=centralus storageAccountName=$(storageAccountName)